#!/bin/bash

export PREFIX="$HOME/.local/cross"
export TARGET=aarch64-elf
export PATH="$PATH:$PREFIX/bin"

mirror="${MIRROR:-https://ftp.gnu.org/gnu}"

binutils_version=2.44
gcc_version=14.3.0

set -xe

wget $mirror/binutils/binutils-$binutils_version.tar.xz
tar -xf binutils-$binutils_version.tar.xz

mkdir build-binutils
pushd build-binutils

../binutils-$binutils_version/configure \
  --target=$TARGET \
  --prefix="$PREFIX" \
  --with-sysroot \
  --disable-nls \
  --disable-werror

make -j $(nproc)
make install

popd

rm -rf \
  binutils-$binutils_version.tar.xz \
  binutils-$binutils_version \
  build-binutils

if ! command -v $TARGET-as >/dev/null 2>&1; then
  echo "$TARGET-as is not in the PATH"
  exit 1
fi

wget $mirror/gcc/gcc-$gcc_version/gcc-$gcc_version.tar.xz
tar -xf gcc-$gcc_version.tar.xz

mkdir build-gcc
pushd build-gcc

../gcc-$gcc_version/configure \
  --target=$TARGET \
  --prefix="$PREFIX" \
  --disable-nls \
  --enable-languages=c,c++ \
  --without-headers \
  --disable-hosted-libstdcxx

make -j $(nproc) all-gcc
make -j $(nproc) all-target-libgcc
make -j $(nproc) all-target-libstdc++-v3
make install-gcc
make install-target-libgcc
make install-target-libstdc++-v3

popd

rm -rf gcc-$gcc_version.tar.xz gcc-$gcc_version build-gcc
